### ISSUE TITLE
Does not work anymore with SVG elements

### ISSUE THREAD

**Issue by dlindenkreuz** [littlebits/react-popover#148]
Since 0.5.x, react-popover does not work anymore with a `<path>` or any other SVG element as `target` (astonishingly enough, it did before).

From now on, react-popover adds a `<div>` wrapper around its target which breaks the SVG layout.

```ts
return <svg>
  <path d="..." />
  <Popover><path d="..." /></Popover>
</svg>
// → DOM: <svg>...<div><path d="..."></path></div></svg>
```

[Internally, react-popover attaches a ref to the wrapper div.](https://github.com/littlebits/react-popover/blob/11427697c729cf7be2b9f622da04afc759f1f332/lib/index.js#L463) It would be unfeasible to attach the ref directly to `<Popover>`'s children using `React.cloneElement` because `cloneElement` preserves existing refs.

The only easy solution I can see right now is to introduce an optional prop that allows specifying a wrapper element type (string). People with SVG usage scenarios would then use `g`, everyone else uses `div` by default. `<Popover wrapperElementType="g">`

Thoughts?

**Comment by jasonkuhrt** [comment]
@dlindenkreuz Great find and reporting, thanks! The reason we wrap is to support `ref` access. We did not do that before because we used `ReactDOM.findDOMNode`.

Options:

* Try going back to [`findDOMNode`](https://reactjs.org/docs/react-dom.html#finddomnode)
* Your proposed solution
* Allow passed children to declare their support for a ref (not sure exactly how)

I think option 1 above is the best path forward. A case of not using ref to keep the API simple for consumers is worthwhile IMO. I don't see any downsides currently other than going against the best practice, but again this is a reasonable exception.

**Comment by jasonkuhrt** [comment]
I'm going to consider this issue a bug as it breaks previous behaviour in an unexpected way.

**Comment by jasonkuhrt** [comment]
@dlindenkreuz Thanks for reporting! Try `0.5.3` that I just published.

**Comment by dlindenkreuz** [comment]
Sweet, thx for the quick fix!
