### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by amok** [littlebits/react-popover#75]
I see opened important PRs
Does author support this project?

**Comment by GertjanReynaert** [comment]
@jasonkuhrt are you or anyone else still maintaining this project?

**Comment by amok** [comment]
this issue is 29 days old
seems answer is "No"

**Comment by jasonkuhrt** [comment]
Hi, sorry for the lack of reply. I stopped working at littleBits in January and it seems that this project has been almost entirely neglected since then. If littleBits is open to migrating this project to my Github and NPM account I would be willing to try and give this project some proper attention and be more open/reactive to including other collaborators. @sch sorry to bother you but I don't know who else to ping about this. Thanks and sorry again to anyone who was inconvenienced by inactivity on this project.

**Comment by cjke** [comment]
If you don't get a reply, you could just fork it, and leave a comment here, saying you are continuing development in repo jasonkuhrt/xyz

I understand it might cause a bit of confusion - but better than zero maintenance

**Comment by tnrich** [comment]
So, any recent movement on this front? This seems like the nicest popover solution for react I've seen so far.

**Comment by clayne11** [comment]
`material-ui` has a much nicer popover. I would recommend using it instead and it's actively maintained.

**Comment by jasonkuhrt** [comment]
@cjke Certainly but its not a route I would personally like to take. The `npm` namespace is an issue to. @tnrich Nothing. @clayne11 Thanks for linking to an alternative.

**Comment by mystrdat** [comment]
@clayne11 Hardly the same thing. This popover smartly adjusts the position and arrow, the material-ui variant is much more primitive.

**Comment by clayne11** [comment]
The `material-ui` popover also adjusts it's position based on the screen and scroll. The animation is also way better than the one for `react-popover`.

It's a pretty close replacement and by far the best popover I've seen in React. If you have a better suggestion feel free to link to it.

**Comment by mystrdat** [comment]
@clayne11 Well, the popover stutters heavily when it repositions (Chrome 55) and it lacks the arrow pointing to element center, which wouldn't be exactly simple to hack in. I'd love an alternative tbh.

**Comment by clayne11** [comment]
The arrow is against the Material Design spec, hence why it isn't there.

I think the only option at this point is the make a new component because unfortunately (and surprisingly!) there isn't much else out there in the React ecosystem.

To be honest, `react-popover` seems dead and the code isn't very good anyways. It's extremely over-complicated. A much better alternative could be made that's much easier to maintain.

**Comment by mystrdat** [comment]
@clayne11 Seems that @jasonkuhrt would be interested in continuing this plugin, maybe that would be an option too. I'm not entirely thrilled by the React ecosystem myself, so I would pass on writing a new plugin myself.

**Comment by jasonkuhrt** [comment]
Once again sorry for the disappointments, be it about code quality or activity. I did what I could at the time a long time ago. I'm mulling a possible `react-popover2` under my account but this is still TBD. I like that there is a need I can help contribute toward so that would be my main motivation.

**Comment by xRapidDavex** [comment]
@clayne11 

> The arrow is against the Material Design spec, hence why it isn't there.

Do you have a source on that?

**Comment by clayne11** [comment]
https://material.google.com/components/tooltips.html#tooltips-usage

**Comment by xRapidDavex** [comment]
@clayne11 I didn't know this existed, thanks so much!

**Comment by oyeanuj** [comment]
[React-Popover2](https://github.com/torchup/react-popover2) is new place, it seems!

**Comment by jasonkuhrt** [comment]
Hey everyone, @sch gave me admin rights to this repo again a few days ago. This coincides with me getting back into JavaScript/React work after taking a long paternity leave and wild adventures into Haskell-land. I am excited to work on this project again. With a bit of luck, sweat, and help I hope to turn it into a great popover–one that you will want to use. I'll be looking for help. If you are interested the best way in is via PRs until trust is established and we formalize collaboration via membership.

My first steps will be to review the backlog, publish my priorities and feature-order roadmap (no time commitments).

Cheers everyone! CC @toddlawton would love to collaborate on this with you if you are interested!

**Comment by toddlawton** [comment]
@jasonkuhrt I'd be glad to support the project!

**Comment by jasonkuhrt** [comment]
Unfortunately for a long time the answer was no, this project is not alive. However that's all changed now. The undead hath cometh!

**Comment by lauterry** [comment]
Glad to have @jasonkuhrt back on this project ! 👍

**Comment by jasonkuhrt** [comment]
@lauterry I've been working away on an upcoming [blog post detailing the layout engine](https://jasonkuhrt.gitbooks.io/blog/2-react-popover-layout-system/). This was necessary for me to jump back in and take the project further. Its almost done. My short-term plan is still to try and make a quick release fixing low hanging fruit though.

**Comment by lauterry** [comment]
@jasonkuhrt We, at PerfectStay.com, are relying on react-popover to display filters for flights. We are really glad that react-popover has its maintainer back !


![capture d ecran 2017-03-03 a 09 31 13](https://cloud.githubusercontent.com/assets/1374238/23543808/389d7848-fff4-11e6-86b6-94cf22a9141f.jpg)
